// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6dgI1EdiJG4HKoXBxVmhybx8x54y3BMA',
    appId: '1:186419207046:android:ad6fe4d0488c1cd9aa6a07',
    messagingSenderId: '186419207046',
    projectId: 'sysai-273eb',
    databaseURL: 'https://sysai-273eb-default-rtdb.firebaseio.com',
    storageBucket: 'sysai-273eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQUxFVYvJOB7F1iYzmsgCxI1D-LKzE7Ts',
    appId: '1:186419207046:ios:b6f12bcf6891973eaa6a07',
    messagingSenderId: '186419207046',
    projectId: 'sysai-273eb',
    databaseURL: 'https://sysai-273eb-default-rtdb.firebaseio.com',
    storageBucket: 'sysai-273eb.appspot.com',
    iosClientId: '186419207046-po2kfrdt494r9egju4hjq71did7at416.apps.googleusercontent.com',
    iosBundleId: 'com.example.itccMobile',
  );
}
